src/java/model/FestivalManagerBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import controller.helper.TopRatedFestivalAdapter;
import controller.helper.TopSellingFestivalAdapter;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import model.dao.CommentDAO;
import model.dao.FestivalDAO;
import model.dao.FestivalEventDAO;
import model.dao.FestivalNameDAO;
import model.dao.MessageDAO;
import model.dao.RatingDAO;
import model.dao.TicketDAO;
import model.entity.Festival;
import model.entity.FestivalEvent;
import model.entity.FestivalName;
import model.entity.Message;
import model.entity.Ticket;
import model.entity.helpers.FestivalStatus;

/**
 *
 * @author TajnaSluzba
 */
@ManagedBean
@ApplicationScoped
public class FestivalManagerBean implements Serializable {

    @ManagedProperty(value = "#{festivalDAO}")
    private FestivalDAO festivalDAO;

    @ManagedProperty(value = "#{festivalNameDAO}")
    private FestivalNameDAO festivalNameDAO;

    @ManagedProperty(value = "#{festivalEventDAO}")
    private FestivalEventDAO festivalEventDAO;

    @ManagedProperty(value = "#{ticketDAO}")
    private TicketDAO ticketDAO;

    @ManagedProperty(value = "#{commentDAO}")
    private CommentDAO commentDAO;

    @ManagedProperty(value = "#{ratingDAO}")
    private RatingDAO ratingDAO;

    @ManagedProperty(value = "#{messageDAO}")
    private MessageDAO messageDAO;

    public void setMessageDAO(MessageDAO messageDAO) {
        this.messageDAO = messageDAO;
    }
    
    public void setRatingDAO(RatingDAO ratingDAO) {
        this.ratingDAO = ratingDAO;
    }

    public void setCommentDAO(CommentDAO commentDAO) {
        this.commentDAO = commentDAO;
    }

    public void insertNewFestival(Festival festival) {
        festivalDAO.insert(festival);
    }
    
    public void insertUploadedFestival(Festival festival) {
        festivalDAO.insertUploaded(festival);
    }

    public List<Festival> getFestivals() {
        return festivalDAO.getFestivals();
    }

    public List<FestivalName> getAllFestivalNames() {
        return festivalNameDAO.getAllFestivalNames();
    }

    public void setFestivalDAO(FestivalDAO festivalDAO) {
        this.festivalDAO = festivalDAO;
    }

    public void setFestivalNameDAO(FestivalNameDAO festivalNameDAO) {
        this.festivalNameDAO = festivalNameDAO;
    }

    public void addNewFestivalName(FestivalName festivalName) {
        festivalNameDAO.insert(festivalName);
    }

    public FestivalName getFestivalNameByName(String name) {
        return festivalNameDAO.getFestivalByName(name);
    }

    public FestivalName getFestivalNameById(int id) {
        return festivalNameDAO.getFestivalById(id);
    }

    public void setFestivalEventDAO(FestivalEventDAO festivalEventDAO) {
        this.festivalEventDAO = festivalEventDAO;
    }

    public void addFestivalEvent(FestivalEvent festivalEvent) {
        festivalEventDAO.insert(festivalEvent);
    }

    public Festival getFestivalById(int id) {
        return festivalDAO.getFestivalById(id);
    }

    public void addTickets(List<Ticket> tickets) {
        ticketDAO.insert(tickets);
    }

    public void setTicketDAO(TicketDAO ticketDAO) {
        this.ticketDAO = ticketDAO;
    }

    public void addTicket(Ticket ticket) {
        ticketDAO.insert(ticket);
    }

    public List<Festival> search(String name, Date dateFrom, Date dateTo, String place, String performer) {
        return festivalDAO.search(name, dateFrom, dateTo, place, performer);
    }

    public Ticket getTicketById(int id) {
        return ticketDAO.getTicketsById(id);
    }

    public Ticket getFirstDayTicketByFestivalId(int id) {
        return ticketDAO.getFirstDayTicketsByFestivalId(id);
    }

    public Ticket getAllDaysTicketByFestivalId(int id) {
        return ticketDAO.getWholeFestivalTicketByFestivalId(id);
    }

    public void addVisitToFestival(Festival festival) {
        festivalDAO.addVisitToFestival(festival);
    }

    public List<Festival> getNextFiveFestivals() {
        return festivalDAO.nextFiveFestivals();
    }

    public void updateTicket(Ticket ticket) {
        ticketDAO.update(ticket);
    }

    public List<Festival> getTopFiveFestivals() {
        return festivalDAO.getTopFiveFestivals();
    }

    public List<TopSellingFestivalAdapter> getTopSellingFestivals() {
        List<TopSellingFestivalAdapter> festivalAdapter = new ArrayList<>();
        for (Object o : festivalDAO.getTopSellingTicketsFestivals()) {
            TopSellingFestivalAdapter adapter = new TopSellingFestivalAdapter();
            Object[] oo = (Object[]) o;
            adapter.setTotalTickets((long) oo[0]);
            adapter.setId((int) oo[1]);
            adapter.setFestivalName((FestivalName) oo[2]);
            festivalAdapter.add(adapter);
        }
        return festivalAdapter;
    }
    
    public double getAverageRating(Festival festival) {
        return ratingDAO.getAverageRating(festival);
    }
    
    public List<TopRatedFestivalAdapter> getTopFiveRatedFestivals() {
        List<TopRatedFestivalAdapter> festivalAdapter = new ArrayList<>();
        for (Object o : festivalDAO.getTopSellingTicketsFestivals()) {
            TopRatedFestivalAdapter adapter = new TopRatedFestivalAdapter();
            Object[] oo = (Object[]) o;
            adapter.setAverageRating((double) oo[0]);
            adapter.setId((int) oo[1]);
            adapter.setFestivalName((FestivalName) oo[2]);
            festivalAdapter.add(adapter);
        }
        return festivalAdapter;
    }
    
    public void updateFestival(Festival festival) {
        festivalDAO.update(festival);
    }
    
    public void cancelFestival(Festival festival) {
        festival.setStatus(FestivalStatus.CANCELED);
        festivalDAO.update(festival);
    }
    
    public void inserMessage(Message message) {
        messageDAO.insert(message);
    }
}

src/java/model/UserManagerBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import model.dao.CommentDAO;
import model.dao.RatingDAO;
import model.dao.ReservationDAO;
import model.dao.UserDAO;
import model.entity.Comment;
import model.entity.Festival;
import model.entity.Rating;
import model.entity.Reservation;
import model.entity.User;

/**
 *
 * @author TajnaSluzba
 */
@ManagedBean
@ApplicationScoped
public class UserManagerBean implements Serializable {

    @ManagedProperty(value = "#{userDAO}")
    private UserDAO userDao;

    @ManagedProperty(value = "#{reservationDAO}")
    private ReservationDAO reservationDAO;

    @ManagedProperty(value = "#{commentDAO}")
    private CommentDAO commentDAO;

    @ManagedProperty(value = "#{ratingDAO}")
    private RatingDAO ratingDAO;

    public void setRatingDAO(RatingDAO ratingDAO) {
        this.ratingDAO = ratingDAO;
    }

    public void setCommentDAO(CommentDAO commentDAO) {
        this.commentDAO = commentDAO;
    }

    public void setUserDao(UserDAO userDao) {
        this.userDao = userDao;
    }

    public void setReservationDAO(ReservationDAO reservationDAO) {
        this.reservationDAO = reservationDAO;
    }

    public void insertUser(User user) {
        userDao.insert(user);
    }

    public void updateUser(User user) {
        userDao.update(user);
    }

    public User getUser(String username, String password) {
        return userDao.getUser(username, password);
    }

    public boolean isUsernameTaken(String username) {
        return userDao.getUserByUserName(username) != null;
    }

    public boolean isEmailTaken(String email) {
        return userDao.getUserByEmail(email) != null;
    }

    public boolean addReservation(Reservation reservation) {
        return reservationDAO.insert(reservation);
    }

    public int getReservationCountForTicketUser(User user, Festival festival) {
        return reservationDAO.getReservationCountForTicketUser(user, festival);
    }

    public List<Reservation> getReservationsForUser(User user) {
        return reservationDAO.getReservationsForUser(user);
    }

    public List<Reservation> getCancelableReservations(User user) {
        return reservationDAO.getCancelableReservations(user);
    }

    public void cancelReservation(Reservation reservation) {
        reservationDAO.deleteReservation(reservation);
    }

    public boolean checkReservationBlock(User user) {
        return reservationDAO.checkReservationBlock(user);
    }

    public boolean isBlockedFromFestival(User user, Festival festival) {
        return reservationDAO.isUserBlockedFromFestival(user, festival);
    }

    public List<Festival> getCommentedFestivalsForUser(User user) {
        return commentDAO.getCommentedFestivalsForUser(user);
    }

    public void approveReservation(Reservation reservation) {
        reservation.setIsPurchased(true);
        reservationDAO.update(reservation);
    }

    public List<Reservation> getAllReserved() {
        return reservationDAO.getAllReserved();
    }

    public List<User> getLastTenRegistratedUsers() {
        return userDao.getLastTenRegistrated();
    }

    public List<Reservation> getPurchasedReservations(User user) {
        return reservationDAO.getPurchasedReservations(user);
    }

    public boolean isFestivalCommentable(Festival festival, User user) {
        return reservationDAO.isFestivalCommentable(festival, user);
    }

    public void insertRating(Rating rating) {
        ratingDAO.insert(rating);
    }

    public void insertComment(Comment comment) {
        commentDAO.insert(comment);
    }
}

src/java/model/entity/Comment.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.entity;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 *
 * @author TajnaSluzba
 */
@Entity
public class Comment implements Serializable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    private String comment;
    
    @ManyToOne(optional = false)
    @JoinColumn(name = "festival_id", nullable = false, updatable = false)
    private Festival festival;
    
    @ManyToOne(optional = false)
    @JoinColumn(name = "user_id", nullable = false, updatable = false)
    private User user;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Festival getFestival() {
        return festival;
    }

    public void setFestival(Festival festival) {
        this.festival = festival;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    
}

src/java/model/entity/helpers/UserType.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.entity.helpers;

/**
 *
 * @author TajnaSluzba
 */
public enum UserType {
    USER, ADMIN
}

src/java/controller/FestivalBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import model.FestivalManagerBean;
import model.entity.Festival;

/**
 *
 * @author TajnaSluzba
 */
@ManagedBean
public class FestivalBean {
    
    @ManagedProperty(value = "#{festivalManagerBean}")
    private FestivalManagerBean festivalManagerBean;
    
    private List<Festival> festivals;
    
    public void festivalsOnClick() {
        festivals = festivalManagerBean.getFestivals();
    }

    public void setFestivalManagerBean(FestivalManagerBean festivalManagerBean) {
        this.festivalManagerBean = festivalManagerBean;
    }

    public List<Festival> getFestivals() {
        return festivals;
    }

    public void setFestivals(List<Festival> festivals) {
        this.festivals = festivals;
    }
    
}

src/java/controller/UploadFestivalController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import model.entity.Festival;
import org.primefaces.event.FileUploadEvent;
import util.FlashMessage;
import util.parser.CSVParser;

/**
 *
 * @author TajnaSluzba
 */
@ManagedBean
@ViewScoped
public class UploadFestivalController {
    
    @ManagedProperty(value = "#{csvParser}")
    private CSVParser csvParser;
    
    private Festival festival;
    private boolean nextEnabled;
    
    public void handleFileUpload(FileUploadEvent event) {
        try {
            festival = csvParser.parse(event.getFile().getInputstream());
        } catch (ParseException ex) {
            FlashMessage.flash(FacesMessage.SEVERITY_ERROR, "GRESKA!", "");
            Logger.getLogger(UploadFestivalController.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            FlashMessage.flash(FacesMessage.SEVERITY_ERROR, "GRESKA!", "");
            Logger.getLogger(UploadFestivalController.class.getName()).log(Level.SEVERE, null, ex);
        }
        FlashMessage.flash(FacesMessage.SEVERITY_INFO, "Gotovo!", "");
        nextEnabled = true;
    }

    public void setCsvParser(CSVParser csvParser) {
        this.csvParser = csvParser;
    }

    public Festival getFestival() {
        return festival;
    }

    public void setFestival(Festival festival) {
        this.festival = festival;
    }

    public boolean isNextEnabled() {
        return nextEnabled;
    }

    public void setNextEnabled(boolean nextEnabled) {
        this.nextEnabled = nextEnabled;
    }
}

src/java/controller/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import model.entity.User;

/**
 *
 * @author TajnaSluzba
 */
@ManagedBean
@SessionScoped
public class UserController implements Serializable {

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}

web/admin.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <ui:composition template="/templates/template.xhtml">
            <ui:define name="content">


                <h:form>
                    <p:outputPanel rendered="#{userController.user != null &amp;&amp; userController.user.userType == 'ADMIN'}">
                        <br/>
                        <p:messages id="msg" closable="true" autoUpdate="true" showDetail="true" />
                        <br/>
                        <p:panelGrid columns="2">
                            <h:outputText value="Nesto"/>
                            <h:outputText value="Sto"/>
                            <h:outputText value="Vidi"/>
                            <h:outputText value="Ulogovan"/>
                            <p:commandButton value="Logout" action="#{loginController.logout()}" />
                        </p:panelGrid>
                        <br/>
                        <h:outputText value="5 najposećenijih festivala" />
                        <br/>
                        <p:dataTable var="festival" value="#{adminViewController.topFiveVisitedFestivals}" >
                            <p:column headerText="Festival" >
                                <p:link outcome="festival" value="#{festival.festivalName.name}" >
                                    <f:param name="id" value="#{festival.id}" />
                                </p:link>
                            </p:column>
                            <p:column headerText="Broj poseta" >
                                <h:outputText value="#{festival.numberOfVisits}" />
                            </p:column>
                        </p:dataTable>
                        <br/>
                        <h:outputText value="Najviše kupljeno ulaznica" />
                        <br/>
                        <p:dataTable var="adapter" value="#{adminViewController.topFiveSellingFestivals}" >
                            <p:column headerText="Festival" >
                                <p:link outcome="festival" value="#{adapter.festivalName.name}" >
                                    <f:param name="id" value="#{adapter.id}" />
                                </p:link>
                            </p:column>
                            <p:column headerText="Broj prodatih karata" >
                                <h:outputText value="#{adapter.totalTickets}" />
                            </p:column>
                        </p:dataTable>
                        <p:link outcome="reservations" value="Odobri nove rezervacije" />
                        <br/>
                        <p:commandLink action="#{adminViewController.showLastTenUsers()}" value="Pokazi poslednjih 10 korisnika" update="lastTenUsers"/>
                        <br/>
                        <p:commandLink value="Odobri nove slike" action="#{adminViewController.approveAllNewMedia()}" update="msg" />
                        <br/>
                        <p:link outcome="uploadFestival" value="Učitaj festival iz fajla"/>
                        <br/>
                        <br/>
                        <br/>
                        <p:commandButton value="Dodaj festival" action="addFestival" />
                        <p:outputPanel id="lastTenUsers" >
                            <h:outputText value="Poslednjih 10 registrovanih korisnika" rendered="#{adminViewController.showLastTen}" />
                            <p:dataTable var="user" value="#{adminViewController.lastTenRegistratedUsers}" rendered="#{adminViewController.showLastTen}" >
                                <p:column headerText="Korisnicko ime">
                                    <h:outputText value="#{user.username}" />
                                </p:column>
                                <p:column headerText="Datum pristupa">
                                    <h:outputText value="#{user.dateCreated}" >
                                        <f:convertDateTime pattern="dd-MMM-yyyy HH:mm:ss" timeZone="GMT+1" />
                                    </h:outputText>
                                </p:column>
                            </p:dataTable>
                        </p:outputPanel>
                    </p:outputPanel>
                </h:form>
                <p:outputPanel rendered="#{userController.user == null}" style="text-align: center">
                    404 - maybe next time.
                </p:outputPanel>  
            </ui:define>
        </ui:composition>
    </h:body>
</html>

web/comment.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Ostavite komentar</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <f:metadata>
            <f:viewParam name="id" value="#{commentCreateController.festivalId}" />
            <f:viewAction action="#{commentCreateController.setup()}" />
        </f:metadata>
        <p:outputPanel rendered="#{commentCreateController.commendable}">
            <h:form enctype="multipart/form-data">
                <h:outputText value="Upisi komentar"/>
                <br/>
                <p:inputTextarea value="#{commentCreateController.comment.comment}" />
                <br/>
                <h:outputText value="Daj ocenu"/>
                <br/>
                <p:selectOneMenu value="#{commentCreateController.rating.rating}" >
                    <c:forEach var="iter" step="1" begin="1" end="10" >
                        <f:selectItem itemLabel="#{iter}" itemValue="#{iter}" />
                    </c:forEach>
                </p:selectOneMenu>
                <br/>
                <h:outputText value="Dodaj sliku ili video"/>

                <p:fileUpload fileUploadListener="#{commentCreateController.handleFileUpload}" />

                <br/>
                <p:commandButton value="Sačuvaj" action="#{commentCreateController.save()}" />
            </h:form>
        </p:outputPanel>
        <p:outputPanel rendered="#{!commentCreateController.commendable}">
            <h:outputText value="404 - maybe next time" />
        </p:outputPanel>
    </h:body>
</html>

web/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Izmeni festival - #{festivalEditController.festival.festivalName.name}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <f:metadata>
            <f:viewParam name="id" value="#{festivalEditController.festivalId}" />
            <f:viewAction action="#{festivalEditController.setup()}" />
        </f:metadata>
        <h:form>
            <p:outputPanel rendered="#{userController.user != null &amp;&amp; userController.user.userType == 'ADMIN'}">
                <p:outputPanel id="editPanel" >
                    <p:panel rendered="#{!festivalEditController.showMessage}">
                        <p:messages autoUpdate="true" closable="true" showDetail="true" />
                        <h:outputText value="Promeni izvođače" />
                        <br/>
                        <p:dataTable id="myDay" var="festivalSingleDayEvent" value="#{festivalEditController.festivalEventAdapters}">
                            <p:column headerText="Ime izvođača">
                                <h:outputText value="#{festivalSingleDayEvent.festivalEvent.performerName}" rendered="#{!festivalSingleDayEvent.isEditable}" />
                                <p:inputText value="#{festivalSingleDayEvent.festivalEvent.performerName}" rendered="#{festivalSingleDayEvent.isEditable}" required="false" requiredMessage="Unesite ime izvođača" />
                            </p:column>
                            <p:column headerText="Dan" style="width: 5%">
                                <h:outputText value="#{festivalSingleDayEvent.festivalEvent.day}" rendered="#{!festivalSingleDayEvent.isEditable}" />
                                <p:inputText style="width: 50%" value="#{festivalSingleDayEvent.festivalEvent.day}" rendered="#{festivalSingleDayEvent.isEditable}" required="false" requiredMessage="Unesite dan nastupa" />
                            </p:column>
                            <p:column headerText="Datum početka">
                                <h:outputText value="#{festivalSingleDayEvent.festivalEvent.dateFrom}" rendered="#{!festivalSingleDayEvent.isEditable}" />
                                <p:calendar value="#{festivalSingleDayEvent.festivalEvent.dateFrom}" showOn="button" pattern="dd-MMM-yyyy HH:mm:ss" rendered="#{festivalSingleDayEvent.isEditable}" required="false" requiredMessage="Unesite vreme početka nastupa" />
                            </p:column>
                            <p:column headerText="Datum kraja">
                                <h:outputText value="#{festivalSingleDayEvent.festivalEvent.dateTo}" rendered="#{!festivalSingleDayEvent.isEditable}" />
                                <p:calendar value="#{festivalSingleDayEvent.festivalEvent.dateTo}" showOn="button" pattern="dd-MMM-yyyy HH:mm:ss" rendered="#{festivalSingleDayEvent.isEditable}" required="false" requiredMessage="Unesite vreme kraja nastupa" />
                            </p:column>
                            <p:column headerText="Opis">
                                <h:outputText value="#{festivalSingleDayEvent.festivalEvent.description}" rendered="#{!festivalSingleDayEvent.isEditable}" />
                                <p:inputTextarea value="#{festivalSingleDayEvent.festivalEvent.description}" rendered="#{festivalSingleDayEvent.isEditable}" required="true" requiredMessage="Unesite opis nastupa" />
                            </p:column>
                            <p:column>
                                <p:commandButton value="Izmeni" rendered="#{!festivalSingleDayEvent.isEditable}" action="#{festivalEditController.onEdit(festivalSingleDayEvent)}" update="myDay"/>
                                <p:commandButton value="Sačuvaj" rendered="#{festivalSingleDayEvent.isEditable}" action="#{festivalEditController.onSave(festivalSingleDayEvent)}" update="myDay"/>
                                <p:commandButton value="Izbriši" action="#{festivalEditController.onDelete(festivalSingleDayEvent)}" update="myDay" immediate="true" />
                            </p:column>
                        </p:dataTable>
                        <br/>
                        <p:commandButton value="Dodaj izvođača" action="#{festivalEditController.addPerformer()}" update="myDay" />
                        <br/>
                        <br/>
                        <p:commandButton value="Otkaži festival" action="#{festivalEditController.cancelFestival()}" update="messagePanel editPanel" />
                        <p:commandButton value="Potvrdi izmene" action="#{festivalEditController.addMessage()}" update="messagePanel editPanel" />
                    </p:panel>
                </p:outputPanel>
                <p:outputPanel id="messagePanel" >
                    <p:panel rendered="#{festivalEditController.showMessage}">
                        <h:outputText value="Unesite poruku za korisnike" />
                        <br/>
                        <p:inputTextarea value="#{festivalEditController.message.message}" />
                        <br/>
                        <p:commandButton action="#{festivalEditController.confirm()}" value="Potvrdi" />
                    </p:panel>
                </p:outputPanel>
            </p:outputPanel>
        </h:form>
        <p:outputPanel rendered="#{userController.user == null}">
            404 - maybe next time.
        </p:outputPanel>
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="/templates/template.xhtml">
            <ui:define name="content">

                <h:form>
                    <p:panel id="loginPanel">
                        <p:panel rendered="#{userController.user == null}">
                            <p:messages showDetail="true" closable="true" autoUpdate="true" />
                            <p:inputText value="#{loginController.username}" /><br/>
                            <p:password value="#{loginController.password}" /><br/>
                            <p:commandButton id="login" value="Login" action="#{loginController.login()}" /><br/>
                            <p:button value="Registacija" outcome="register" />
                        </p:panel>
                        <p:panel  rendered="#{userController.user != null}" >
                            <h:outputText value="#{userController.user.username}" /><br/>
                            <p:commandButton value="Logout" action="#{loginController.logout()}" update="loginPanel" />
                            <p:commandButton value="Admin dash" action="admin" />
                            <video width="400" controls="controls" >
                                <source src="media/videos/html5_video.mp4" type="video/mp4"  />
                            </video>
                        </p:panel>
                        <br/>
                        <br/>
                        <p:commandButton value="Pretraži festivale" action="search" />
                    </p:panel>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>